
const URLActivity = {
  GetITRRequest: 'http://paytds.com/JsonService/GetITRRequest.aspx',
  FillQuarter: 'http://paytds.com/JsonService/FillQuarter.aspx',
  ITRRequest: 'http://paytds.com/JsonService/ITRRequest.aspx',
  Session: 'http://paytds.com/JsonService/Session.aspx',
  Form16Quarterly: 'http://paytds.com/JsonService/Form16Quarterly.aspx',
  LICAgent: 'http://paytds.com/jsonService/LICAgent.aspx',
  MatchDeviceId: 'http://paytds.com/jsonService/MatchDeviceId.aspx',
  LICAgentDetail: 'http://paytds.com/jsonService/LicAgentDetail.aspx',
  FillCity: 'http://paytds.com/jsonService/FillCity.aspx',
  FillDept: 'http://paytds.com/jsonService/FillDept.aspx',
  PartA_PartBForm16: 'http://paytds.com/jsonService/PartA_PartBForm16.aspx',
  Greeting: 'http://paytds.com/Greetings/SaveDocs.aspx',
  DisplayDocs: 'http://paytds.com/Greetings/DisplayDocs.aspx',
  UploadDocs: 'http://paytds.com/Greetings/UploadDocs.aspx',
  GetCategories: 'http://paytds.com/Greetings/GetCategories.aspx',
  SaveDocs: 'http://paytds.com/Greetings/SaveDocs.aspx',
  DelDocs: 'http://paytds.com/Greetings/DelDocs.aspx',
  SaveCatImages: 'http://paytds.com/Greetings/SaveCatImages.aspx',
  AddCategory: 'http://paytds.com/Greetings/AddCategory.aspx',
  GetCategoriesForUser: 'http://paytds.com/Greetings/GetCategoriesForUser.aspx',
  GetDataDispCatWise: 'http://paytds.com/Greetings/GetDataDispCatWise.aspx',
  DelCat: 'http://paytds.com/Greetings/DelCat.aspx',
  AddMember: 'http://paytds.com/Greetings/AddMember.aspx',
  GetRegisteredAPIMembers:
    'http://paytds.com/Greetings/GetRegisteredAPIMembers.aspx',
  UpdateSorting: 'http://paytds.com/Greetings/UpdateSorting.aspx',
  VerifyUser: 'http://paytds.com/Greetings/VerifyUser.aspx',
  LICDetail: 'http://paytds.com/Greetings/LICDetail.aspx',
  FillTarunPlan: 'http://paytds.com/Greetings/FillTarunPlan.aspx',
  LICPercentage: 'http://paytds.com/Greetings/LICPercentage.aspx',
  GetTarunPlan: 'http://paytds.com/Greetings/GetTarunPlan.aspx',
  FillpolicyTerm: 'http://paytds.com/Greetings/FillpolicyTerm.aspx',
  GetLICJeevanPer: 'http://paytds.com/Greetings/GetLICJeevanPer.aspx',
  RegisterLICAgent: 'http://paytds.com/JsonService/LICAgent.aspx',
  LoginLICAgent: 'https://paytds.com/JsonService/SignUp.aspx',
};
export default URLActivity;
